#!/usr/bin/env perl
use strict;
use warnings;
use utf8;
use YAML::Syck ();
use Getopt::Long qw(:config posix_default no_ignore_case bundling);

my $generator = +{
};

Getopt::Long::GetOptions(
  'type|t=s' => \my $type,
) or exit 2;

die "no input src" unless $#ARGV >= 0;
die "no specify completion type" unless defined $type;
die "$type: is not supported" unless defined $generator->{$type};

my $src = shift;
my $conf = YAML::Syck::LoadFile($src);
print $generator->{$type}($conf);
